"""
Django settings for untitled project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i77r^7(v*=276mjfg-zx5+$=wpp-bc)6h1efe6(5_68uwndcx3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'untitled.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'untitled.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#
# 切换说明：
#   默认使用 SQLite（适合开发/测试）。
#   如需切换到 MySQL，在项目根目录创建 settings_local.py，
#   写入以下内容即可自动覆盖：
#
#   from .settings import *   # noqa
#   DATABASES = {
#       'default': {
#           'ENGINE': 'django.db.backends.mysql',
#           'NAME': 'db129',          # 数据库名，需提前创建
#           'USER': 'root',           # MySQL用户名
#           'PASSWORD': '123456',     # MySQL密码
#           'HOST': '127.0.0.1',      # 数据库主机地址
#           'PORT': 3306,             # 数据库端口
#           'OPTIONS': {
#               'charset': 'utf8mb4',
#           },
#       }
#   }
#
#   此外还需确保 MySQL 中创建的数据库字符集为 utf8mb4：
#   CREATE DATABASE db129 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
#

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 加载本地覆盖配置（settings_local.py）
# 若存在，会覆盖上面 DATABASES 等默认设置，用于生产环境切换 MySQL
try:
    from .settings_local import *  # type: ignore  # noqa: F403
except ImportError:
    pass


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# SimpleUI 配置 — 覆盖缓存菜单，指向正确的模型
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 不使用系统默认菜单
    'menus': [
        {
            'name': '数据总览',
            'icon': 'fas fa-chart-line',
            'models': [
                {
                    'name': '数据总览',
                    'icon': 'fas fa-table',
                    'url': '/admin/app01/airqualityrecord/'
                }
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-user-tag',
                    'url': '/admin/auth/group/'
                }
            ]
        }
    ]
}


LOGIN_URL = "/login/"
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
