# Generated by Django 4.2.16 on 2026-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirQualityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(db_index=True, max_length=50, verbose_name="城市"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "aqi",
                    models.FloatField(blank=True, null=True, verbose_name="AQI指数"),
                ),
                (
                    "quality_level",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="空气质量等级",
                    ),
                ),
                (
                    "pm25",
                    models.FloatField(
                        blank=True, null=True, verbose_name="PM2.5 (μg/m³)"
                    ),
                ),
                (
                    "pm10",
                    models.FloatField(
                        blank=True, null=True, verbose_name="PM10 (μg/m³)"
                    ),
                ),
                (
                    "no2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NO2 (μg/m³)"
                    ),
                ),
                (
                    "so2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="SO2 (μg/m³)"
                    ),
                ),
                (
                    "co",
                    models.FloatField(blank=True, null=True, verbose_name="CO (mg/m³)"),
                ),
                (
                    "o3",
                    models.FloatField(blank=True, null=True, verbose_name="O3 (μg/m³)"),
                ),
            ],
            options={
                "verbose_name": "空气质量记录",
                "verbose_name_plural": "空气质量记录",
                "ordering": ["city", "date"],
                "indexes": [
                    models.Index(
                        fields=["city", "date"], name="app01_airqu_city_407074_idx"
                    )
                ],
            },
        ),
    ]
